### ISSUE TITLE
为什么使用后没有加载分包后的main.dart.js

### ISSUE THREAD

**Issue by sunjianan9900** [TryImpossible/flutter_web_optimizer#1]
命令成功运行了，因为没有上传OSS，我就把上传OSS的脚本取消了，只把文件生成到本地

flutter_web_optimizer optimize --asset-base http://127.0.0.1:8882/ --plugin scripts/upload.dart

但是我看 flutter_service_worker.js 里面也没有修改文件名
然后我运行完分割脚本，用python在 build/web/ 目录下启动 python -m http.server 8882
结果打不开，错误是找不到 main.dart.js ，是哪一步有问题呢？不应该是去找main.dart.js 吧？

![image](https://user-images.githubusercontent.com/10936316/206665745-885f9fde-3e2c-4407-863c-08518ff77fb9.png)
![image](https://user-images.githubusercontent.com/10936316/206665890-9733378a-cb01-4994-92ee-df8b38851fb9.png)

求指教，我先不想自动上传，先手动上传也可以

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.9, on macOS 13.0 22A380 darwin-arm (Rosetta),
    locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] VS Code (version 1.73.0)

```

**Comment by sunjianan9900** [comment]
补充
![image](https://user-images.githubusercontent.com/10936316/206666971-f02e0ec1-0ec1-46ca-ab5c-2c69d717d402.png)

**Comment by TryImpossible** [comment]
@sunjianan9900 ，我看截图你启用了pwa，flutter_web_optimizer 目前不支持pwa的使用，你可以在打包的时候禁用pwa。
flutter build web --web-renderer html --pwa-strategy none

**Comment by sunjianan9900** [comment]
> @sunjianan9900 ，我看截图你启用了pwa，flutter_web_optimizer 目前不支持pwa的使用，你可以在打包的时候禁用pwa。 flutter build web --web-renderer html --pwa-strategy none

我flutter clean以后
lutter build web --web-renderer html --pwa-strategy none
然后再
flutter_web_optimizer optimize --asset-base http://127.0.0.1:8882/ --plugin scripts/upload.dart

结果还是不可以
flutter_service_worker.js 是空白了
但是我看报错还是一样的，main.dart.js找不到，然后应用自flutter.js
而且我看index.html好像没有什么改变？

![image](https://user-images.githubusercontent.com/10936316/206827148-b263aed1-1d72-40c8-923b-a1f0bdbe56c1.png)
![image](https://user-images.githubusercontent.com/10936316/206827165-22c11662-d020-4fdf-af13-14cac4671bce.png)
![image](https://user-images.githubusercontent.com/10936316/206827252-f4db5784-d1f4-4800-8a6d-0e165cf9d382.png)

**Comment by sunjianan9900** [comment]
我clone了项目，在example里面运行了一下上面的步骤，
也是一样的问题，会加载 main.dart.js 不会加载分包。

大佬，example里面的demo项目能不能上传一下build/web目录呀，我看看是哪里不一样？

**Comment by TryImpossible** [comment]
@sunjianan9900 ,看截图请求的index.html和flutter.js都是未经过flutter_web_optimizer修改的，你先检查下本地的build/web文件夹下的index.html和flutter.js是否已被flutter_web_optimizer修改过？
1. 如果已经修改的话，那么你要弄清为啥请求的是未修改的文件，缓存问题？
2. 如果没有修改的话，你可以升级下flutter_web_optimizer插件，再试试

**Comment by sunjianan9900** [comment]
非常感谢，已经解决了！
不添加 --plugin 参数就可以了 😂
这个包很赞！！
