### ISSUE TITLE
Google font  调用的地方没有被 hash 化，文件被 hash 了

### ISSUE THREAD

**Issue by Attiv** [TryImpossible/flutter_web_optimizer#10]
![CleanShot 2023-02-13 at 22 12 43@2x](https://user-images.githubusercontent.com/15698129/218481210-15b7e965-d0e2-469e-97ea-c6637cccf1e8.png)
![CleanShot 2023-02-13 at 22 13 49@2x](https://user-images.githubusercontent.com/15698129/218481472-cf63c18e-40a4-4698-ab8a-d99feebf33d2.png)

或者加个命令把一些文件排除 hash

**Comment by TryImpossible** [comment]
@Attiv ,是使用了单独的字体文件嘛

**Comment by Attiv** [comment]
> TryImpossible

@TryImpossible  是的，下载到本地的 google fonts

**Comment by Attiv** [comment]
同一个文件夹下有一些图片哈希后可以找到，有些在代码里没有哈希

**Comment by Attiv** [comment]
`png` 在代码里没有被哈希，`svg` 没问题

**Comment by TryImpossible** [comment]
@Attiv ,你能提供个demo吗？

**Comment by TryImpossible** [comment]
@Attiv ,v1.1.10版本提供 --hash-filter-regexp参数过滤文件
