### ISSUE TITLE
--asset-base 参数如何配置为访问本地文件

### ISSUE THREAD

**Issue by Hu-Wentao** [TryImpossible/flutter_web_optimizer#12]
没有引入图片等资源。

命令如下

```shell
dart pub global activate peanut 
flutter build web 
## 没有使用图片等资源，因此直接沿用示例中的 asset-base
flutter pub run flutter_web_optimizer optimize --asset-base http://192.168.101.93:9091/app/
dart pub global run peanut -b prod_web
```

**Comment by Hu-Wentao** [comment]
--asset-base 尝试过 `/`,`./`,`.`都没有起作用

**Comment by TryImpossible** [comment]
@Hu-Wentao ,能提供online demo嘛，就目前这样的描述无法定位问题

**Comment by Hu-Wentao** [comment]
https://github.com/Hu-Wentao/test_web.git

也不算是peanut的问题。就是想问一下，--asset-base参数要怎么配置才能允许访问本地文件，这个项目里面的 web_released 和 web_optimizer 分别是优化前和优化后的。
优化命令为
```shell
flutter pub run flutter_web_optimizer optimize --asset-base ./
```

**Comment by TryImpossible** [comment]
`<script>
    // window.addEventListener('load', function(ev) {
    //   // Download main.dart.js
    //   _flutter.loader.loadEntrypoint({
    //     serviceWorker: {
    //       serviceWorkerVersion: serviceWorkerVersion,
    //     },
    //     onEntrypointLoaded: function(engineInitializer) {
    //       engineInitializer.initializeEngine().then(function(appRunner) {
    //         appRunner.runApp();
    //       });
    //     }
    //   });
    // });
    window.addEventListener('load', function (ev) {
      // Download main.dart.js
      _flutter.loader.loadEntrypoint({
        serviceWorker: {
          serviceWorkerVersion: serviceWorkerVersion,
        }
      }).then(function (engineInitializer) {
        return engineInitializer.initializeEngine();
      }).then(function (appRunner) {
        return appRunner.runApp();
      }).then(function (app) {
        // Wait a few milliseconds so users can see the "zoooom" animation
        // before getting rid of the "loading" div.

      });
    });
  </script>`
@Hu-Wentao ,fluter_web_optimizer插件目前还没有适配3.7版本，启动app的方法只能沿用旧版的，见以上代码

**Comment by Hu-Wentao** [comment]
替换了web/下的`index.html`文件内的相关内容，clean再build之后，使用 `flutter pub run flutter_web_optimizer optimize --asset-base ./` 或者 `flutter pub run flutter_web_optimizer optimize --asset-base .`都没有成功啊，还是白屏

**Comment by Hu-Wentao** [comment]
@TryImpossible 
https://github.com/Hu-Wentao/test_web.git 更新了html内容，web_optimizer内用的地址是 `.`

**Comment by Hu-Wentao** [comment]
@TryImpossible 
关于 flutter_web_optimizer 支持的版本，最新是多少呢？

**Comment by Hu-Wentao** [comment]
@TryImpossible 手动测试了一下 3.3.10可以正常使用。这个优化可以指定是否使用canvas吗？

**Comment by TryImpossible** [comment]
> @TryImpossible 关于 flutter_web_optimizer 支持的版本，最新是多少呢？

3.3.10，3.7版本后需要将index.html中app启动方法修改为旧版本的

**Comment by TryImpossible** [comment]
> @TryImpossible 手动测试了一下 3.3.10可以正常使用。这个优化可以指定是否使用canvas吗？

目前不支持。
