### ISSUE TITLE
json格式的文件优化后提示404

### ISSUE THREAD

**Issue by rhgzs** [TryImpossible/flutter_web_optimizer#14]
使用flutter pub run flutter_web_optimizer optimize ./

json格式的文件，打包后提示404找不到文件，查看目录的文件名已hash化，并且flutter_web_optimizer中也有对应的键值对

**Comment by TryImpossible** [comment]
我猜测读取json文件还是未hash的文件名，应该这个json文件不需要hash，可能通过--hash-filter-regexp参数过滤此文件
