### ISSUE TITLE
当--asset-base为'./'时，生成的flutter_web_optimizer.dart重写了原生方法导致有些外部引入的第三方js库属性没有赋值上去。

### ISSUE THREAD

**Issue by liyingte998** [TryImpossible/flutter_web_optimizer#18]
var _setAttribute = element.setAttribute;
        element.setAttribute = function () {
          var args = Array.prototype.slice.call(arguments);
          // if (args[0] === 'src') {
          //   //do something here
          //   console.log('setAttribute', args[1])
          // }
          _setAttribute.apply(element, args);
        }
请问该如何修改

**Comment by TryImpossible** [comment]
@liyingte998 ,你能提供demo吗？如果我重现不了，我无法去修改

**Comment by liyingte998** [comment]
很抱歉无法单独抽离这个有问题的功能出来。
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/129733164/470e8ad1-fd93-4088-bd11-44b0e0b7bc43)
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/129733164/28d774a6-22bc-421e-a66d-f863d9b1e6d2)
以上两张图是跟问题有关的。


以下是正常赋值后的
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/129733164/3d6f1f17-2320-4914-92ce-2ddd6344c3c0)
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/129733164/4f941d9c-48d1-4d5c-b38c-42eb3e141e93)
