### ISSUE TITLE
404

### ISSUE THREAD

**Issue by wenchaosong** [TryImpossible/flutter_web_optimizer#19]
<img width="748" alt="Untitled" src="https://github.com/TryImpossible/flutter_web_optimizer/assets/16938075/a902d6ad-70e8-4d36-81f9-4a5b4c09d36e">

用的最新版本    1.2

flutter 版本 3.10

用的命令
flutter pub run flutter_web_optimizer optimize --asset-base https://..........

**Comment by TryImpossible** [comment]
抱歉，目前还没有在flutter 3.10上测试过，应该是不支持

**Comment by wenchaosong** [comment]
@TryImpossible  那能升级一个版本吗
