### ISSUE TITLE
大佬可以考虑把flutter build web命令也加进去呀，不然要跑两个命令哎

### ISSUE THREAD

**Issue by LeeCareFree** [TryImpossible/flutter_web_optimizer#2]

**Comment by TryImpossible** [comment]
flutter_web_optimizer工具是针对flutter build web 打包产物作的优化，从职责上来说这是两个独立的东西，不应该耦合在一起。
你要是仅仅只想运行一个命令，可以自己写个shell，例如：flutter build web --web-renderer html && flutter pub run flutter_web_optimizer optimize --asset-base xxx
