### ISSUE TITLE
Demo can not load jpeg or png when using flutter 3.10

### ISSUE THREAD

**Issue by windows7lake** [TryImpossible/flutter_web_optimizer#20]
```
flutter build web --web-renderer html
flutter pub run flutter_web_optimizer optimize --asset-base ''
```
Success:  Build the example with flutter 3.7, jpeg or jpeg loads normal.
Failed: Build the example with flutter 3.10, jpeg or jpeg loads fail.

**Comment by TryImpossible** [comment]
sorry, it's not supported flutter 3.10

**Comment by iBinbro** [comment]
> 

啥时候支持3.10版本呀，看迭代说明，web有优化canvaskit以及相关的大小😁

**Comment by TryImpossible** [comment]
@windows7lake @iBinbro ，flutter_web_optimizer: ^1.3.0  is compatible with Flutter 3.10
