### ISSUE TITLE
Uncaught TypeError: a.substring is not a function

### ISSUE THREAD

**Issue by Pirer24** [TryImpossible/flutter_web_optimizer#23]
Hi! 
I want to optimize my Flutter web, but the substring has a problem.
<img width="1035" alt="Zrzut ekranu 2023-07-21 o 14 59 45" src="https://github.com/TryImpossible/flutter_web_optimizer/assets/36137210/3673371e-8d48-4afa-b703-4c1b2cdb610f">

Commands that I used:
```
flutter gen-l10n
flutter build web -t lib/main_dev.dart --web-renderer html
flutter pub run flutter_web_optimizer optimize --asset-base ./
```
```
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.3.1 22E772610a darwin-arm64, locale pl-PL)
    • Flutter version 3.10.6 on channel stable at /opt/homebrew/Caskroom/flutter/2.10.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1
```

**Comment by TryImpossible** [comment]
@Pirer24 , Are you sure this problem is due to flutter_ web_optimizer plugin?

**Comment by Pirer24** [comment]
Yes, because before the optimization app is working

**Comment by TryImpossible** [comment]
give me a demo please

**Comment by TryImpossible** [comment]
@Pirer24 , you could try flutter_web_optimizer 1.4.0 version
