### ISSUE TITLE
图片没有正确调用hash后的链接

### ISSUE THREAD

**Issue by LcongGitHub** [TryImpossible/flutter_web_optimizer#24]
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/11864086/a4c180ab-1a98-46d2-8151-7fb42551eaee)
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/11864086/be9f8979-5b2e-4b9a-a1b4-e58899940b00)
您好，能帮忙看看吗？ http://matata.uat.egatee.net/ ，其中JS是有效果的，
好像是因为图片没有调用正确的hash后的名称。AssetManifest有修改对应的hash映射，没有生效。

现在调用的链接
https://matata-cdn.uat.egatee.net/assets/packages/common_lib/lib/assets/images/tabbar/tabbar_home_normal.png
应该调用下面这个链接才对：
https://matata-cdn.uat.egatee.net/assets/packages/common_lib/lib/assets/images/tabbar/tabbar_home_normal.22208bf4.png
没有调用正确的hash后的图片导致的，请问需要修改什么地方吗？

**Comment by TryImpossible** [comment]
@LcongGitHub ,请说明你使用的flutter版本和flutter_web_optimizer版本，目前我访问你的网站是没有加载AssetManifest.json或者AssetManifest.bin文件，导致图片加载不出来

**Comment by TryImpossible** [comment]
请说明你使用的flutter版本和flutter_web_optimizer版本，目前我访问你的网站是没有加载AssetManifest.json或者AssetManifest.bin文件，导致图片加载不出来

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LcongGitHub ***@***.***&gt;
发送时间: 2023年7月24日 11:27
收件人: TryImpossible/flutter_web_optimizer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [TryImpossible/flutter_web_optimizer] 图片没有正确调用hash后的链接 (Issue #24)





 

 
 您好，能帮忙看看吗？ http://matata.uat.egatee.net/ ，其中JS是有效果的，
 好像是因为图片没有调用正确的hash后的名称。AssetManifest有修改对应的hash映射，没有生效。
 
现在调用的链接
 https://matata-cdn.uat.egatee.net/assets/packages/common_lib/lib/assets/images/tabbar/tabbar_home_normal.png
 应该调用下面这个链接才对：
 https://matata-cdn.uat.egatee.net/assets/packages/common_lib/lib/assets/images/tabbar/tabbar_home_normal.22208bf4.png
 没有调用正确的hash后的图片导致的，请问需要修改什么地方吗？

**Comment by LcongGitHub** [comment]
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/11864086/a4abffb7-bd9a-4229-a684-9b9b80d502c7)
fluttter版本：3.7.3
flutter_web_optimizer版本：1.2.0

**Comment by TryImpossible** [comment]
@LcongGitHub ，AssetManifest.json不加载的问题估计你得自己去看，除非你能给我个复现的demo

**Comment by LcongGitHub** [comment]
https://github.com/LcongGitHub/cdn_demo
您好，我上传了一个简单的demo，能帮忙看看吗？

**Comment by TryImpossible** [comment]
![screenshot-20230812-022529](https://github.com/TryImpossible/flutter_web_optimizer/assets/23582577/1ee0b2bb-36df-474a-8209-b8f99db70b55)
@LcongGitHub ,你的demo没有问题

**Comment by LcongGitHub** [comment]
已收到！！！

**Comment by LcongGitHub** [comment]
已收到！！！
