### ISSUE TITLE
每次更新删除旧的文件导致报错。

### ISSUE THREAD

**Issue by liyingte998** [TryImpossible/flutter_web_optimizer#25]
每次生成的文件名字都不一样，每次更新都会把旧的文件给删了。更新后第一次进网页可能读的还是上一次缓存的文件名，导致找不到文件报错卡在启动页。
请问这种情况应该怎么处理。

**Comment by TryImpossible** [comment]
文件哈希是对文件内容md5，你文件没有变化的话，文件名字是不会变的

**Comment by liyingte998** [comment]
我每次生成的flutter_web_optimizer.js名字都不一样，所以项目更新是不是最好覆盖重名，不手动删除旧文件。

**Comment by TryImpossible** [comment]
直接覆盖更新即可
