### ISSUE TITLE
大佬，canvaskit渲染模式下报错

### ISSUE THREAD

**Issue by Pianzhous** [TryImpossible/flutter_web_optimizer#26]
大佬，是不支持canvaskit渲染模式吗？报了这个错
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/55571229/80a67391-07dd-4801-a4e4-811f27037267)

**Comment by TryImpossible** [comment]
目前不支持canvaskit渲染模式

**Comment by Pianzhous** [comment]
好的，谢谢大佬

**Comment by liyingte998** [comment]
近期考虑支持canvaskit吗？flutter_web_optimizer 1.1.12 ；Flutter 3.3.10可以运行canvaskit

**Comment by TryImpossible** [comment]
@liyingte998 ，周末看下

**Comment by navyzhou926** [comment]
> @liyingte998 ，周末看下

大佬有时间解决下canvaskit兼容问题不，flutter3.16及以后版本

**Comment by navyzhou926** [comment]
> @TryImpossible why does the code give issues when it comes to canvaskit rendering, any root cause problem?

@TryImpossible 把项目中的flutter3.10的flutter.js换成flutter3.16的打包版本中的flutter.js修改下是可以用的，需要帮忙尽快支持到项目中

**Comment by t0uh33d** [comment]
> > @TryImpossiblewhy does the code give issues when it comes to canvaskit rendering, any root cause problem?
> 
> @TryImpossibleReplace the flutter.js of flutter3.10 in the project with the flutter.js in the packaged version of flutter3.16. After modification, canvaskit can be used. I need help to support it in the project as soon as possible.

could you please share the `flutter.js` file that you may have modified and replaced?

**Comment by navyzhou926** [comment]
> > > @TryImpossiblewhy does the code give issues when it comes to canvaskit rendering, any root cause problem?
> > 
> > 
> > @TryImpossibleReplace the flutter.js of flutter3.10 in the project with the flutter.js in the packaged version of flutter3.16. After modification, canvaskit can be used. I need help to support it in the project as soon as possible.
> 
> could you please share the `flutter.js` file that you may have modified and replaced?

1、flutter build web打包后，将flutter.js单独保存到临时目录
2、执行flutter_web_optimizer生成相关文件
3、将第1步打包生成的flutter.js替换第2步flutter_web_optimizer自动生成的flutter.js，然后修改flutter.js文件里的main.dart.js引用的生成的hash文件名，就可以了
4、canvaskit打包运行可能flutter_web_optimizer引用的flutter.js不是新版本的，所以可能导致打包后运行报错，建议项目作者抽空兼容下flutter3.16

**Comment by TryImpossible** [comment]
@Pianzhous @navyzhou926 @liyingte998 ，1.4.0版本适配flutter 3.16版本 ，支持canvaskit模式

**Comment by TryImpossible** [comment]
> > > @TryImpossiblewhy does the code give issues when it comes to canvaskit rendering, any root cause problem?
> > 
> > 
> > @TryImpossibleReplace the flutter.js of flutter3.10 in the project with the flutter.js in the packaged version of flutter3.16. After modification, canvaskit can be used. I need help to support it in the project as soon as possible.
> 
> could you please share the `flutter.js` file that you may have modified and replaced?

@t0uh33d ，https://github.com/TryImpossible/flutter_web_optimizer/blob/main/lib/src/optimize/flutter.js.dart

**Comment by TryImpossible** [comment]
> @TryImpossible why does the code give issues when it comes to canvaskit rendering, any root cause problem?

@t0uh33d ，you could need flutter_web_optimizer 1.4.0 version

**Comment by navyzhou926** [comment]
> @Pianzhous @navyzhou926 @liyingte998 ，1.4.0版本适配flutter 3.16版本 ，支持canvaskit模式

执行flutter_web_optimizer报错

环境信息：
Flutter (Channel stable, 3.16.9, on macOS 14.2.1 23C71 darwin-arm64, locale zh-Hans-CN)
    • Flutter version 3.16.9 on channel stable at /Users/navyzhou/Projects/Library/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 41456452f2 (4 weeks ago), 2024-01-25 10:06:23 -0800
    • Engine revision f40e976bed
    • Dart version 3.2.6
    • DevTools version 2.28.5

执行flutter_web_optimizer报错信息（使用html和canvaskit打包都报错）：
navyzhou@MacBook:~/git/flutter_test$ dart run flutter_web_optimizer optimize --asset-base ./ --enable-pwa false
Building package executable... 
Built flutter_web_optimizer:flutter_web_optimizer.
start web optimize
hashing file: /Users/navyzhou/git/flutter_test/build/web/icons/Icon-192.png
hashed file name: Icon-192.ac9a721a.png
hashing file: /Users/navyzhou/git/flutter_test/build/web/icons/Icon-maskable-192.png
hashed file name: Icon-maskable-192.c457ef57.png
hashing file: /Users/navyzhou/git/flutter_test/build/web/icons/Icon-maskable-512.png
hashed file name: Icon-maskable-512.301a7604.png
hashing file: /Users/navyzhou/git/flutter_test/build/web/icons/Icon-512.png
Unhandled exception:
Invalid argument (Not a byte value at index 1: 0x-5c): _Int8ArrayView
#0      _Base64Encoder.encodeChunk (dart:convert/base64.dart:374:5)
#1      _Base64Encoder.encode (dart:convert/base64.dart:328:9)
#2      Base64Encoder.convert (dart:convert/base64.dart:243:26)
#3      Codec.encode (dart:convert/codec.dart:25:32)
#4      OptimizeCommand._hashAssets.hashAssetsDir (package:flutter_web_optimizer/src/optimize/optimize_command.dart:493:30)
#5      OptimizeCommand._hashAssets (package:flutter_web_optimizer/src/optimize/optimize_command.dart:579:5)
#6      OptimizeCommand.run (package:flutter_web_optimizer/src/optimize/optimize_command.dart:116:5)
<asynchronous suspension>
#7      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>

**Comment by TryImpossible** [comment]
> canvaskit
提供个demo

**Comment by navyzhou926** [comment]
> > canvaskit
> > 提供个demo


找到原因了，base64.encode需要用Uint8List，而不能用Int8List，因为encode的数据只能是0~255，而不能是有符号的，optimize_comand.dart改成如图即可，已验证没有问题了，请帮忙尽快修改
![图片](https://github.com/TryImpossible/flutter_web_optimizer/assets/510979/531f0b9a-1327-4d78-9855-ba5b87096b5d)

**Comment by TryImpossible** [comment]
> > > canvaskit
> > > 提供个demo
> 
> 找到原因了，base64.encode需要用Uint8List，而不能用Int8List，因为encode的数据只能是0~255，而不能是有符号的，optimize_comand.dart改成如图即可，已验证没有问题了，请帮忙尽快修改 ![图片](https://private-user-images.githubusercontent.com/510979/306160471-531f0b9a-1327-4d78-9855-ba5b87096b5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MjQ0MTIsIm5iZiI6MTcwODQyNDExMiwicGF0aCI6Ii81MTA5NzkvMzA2MTYwNDcxLTUzMWYwYjlhLTEzMjctNGQ3OC05ODU1LWJhNWI4NzA5NmI1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMFQxMDE1MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzVlOTRhMmRjNmM2MWI3NzIwMzQyODhlMjIzMDQ4N2U2MWU2ZThiNjMyNWZkYzVhOWVjNjNmOWQ1ZmI5MDM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NQEwsl--HbpO1ln-5_812IMDl0S7SzsyKyTNmAl7HjY)

已修复，请使用1.4.1版本
