### ISSUE TITLE
加载页面会停顿

### ISSUE THREAD

**Issue by tabian** [TryImpossible/flutter_web_optimizer#27]
![image](https://github.com/TryImpossible/flutter_web_optimizer/assets/24467334/b04094a7-c079-4564-98db-1d70c7d05ff2)

上边图片是我加载https://tryimpossible.github.io/flutter_web_optimizer您的官方demo,会首先加载红色数据，停顿一段时间后再加载下边数据。这会让用户看起来加载缓慢。能问下具体什么原因吗？怎样解决呢

**Comment by TryImpossible** [comment]
flutter build web --pwa-strategy=none ，禁用pwa就不用加载了
