### ISSUE TITLE
Flutter3.16现在main.dart.js加载的是AssetManifest.bin.json文件，所以插件生成的AssetManifest.bin要修改下，不然不能加载资源文件

### ISSUE THREAD

**Issue by navyzhou926** [TryImpossible/flutter_web_optimizer#29]
1、Flutter3.16现在加载的是AssetManifest.bin.json文件，所以插件生成的AssetManifest.bin要修改下，不然不能加载资源文件
2、Flutter3.13经过测试是没有问题的
3、canvaskit模式在Flutter3.16和3.13，插件都不支持哦

**Comment by navyzhou926** [comment]
此次提交修改的：
https://github.com/flutter/flutter/pull/131382

**Comment by navyzhou926** [comment]
目前也可以手动解决此问题（自己写脚本）：
1、执行flutter_web_optimizer，生成AssetManifest.bin
2、使用base64将AssetManifest.bin文件转成base64编码的AssetManifest.bin.json文件
3、将AssetManifest.bin.json首尾各添加1个字符引号"，如AssetManifest.bin.json里的内容为123，则变成"123"，再保存
4、这样Flutter3.16的html打包也可以正常使用，不过canvaskit还是不行，待大佬解决

**Comment by BelongsH** [comment]
> 目前也可以手动解决此问题（自己写脚本）： 1、执行flutter_web_optimizer，生成AssetManifest.bin 2、使用base64将AssetManifest.bin文件转成base64编码的AssetManifest.bin.json文件 3、将AssetManifest.bin.json首尾各添加1个字符引号"，如AssetManifest.bin.json里的内容为123，则变成"123"，再保存 4、这样Flutter3.16的html打包也可以正常使用，不过canvaskit还是不行，待大佬解决

当我升级上来的时候发现了一个问题
1. 本身项目里面有做OSS，包括 AssetManifest文件
2. 在处理OSS的时候，会把静态资源HASH掉。
3. 目前发现AssetManifest.bin.json 没有办法替换hash。他在框架内步引用。
大佬是否有同样的疑问呢？

**Comment by BelongsH** [comment]
3.16.5 的版本AssetManifest.bin.json的请求是写死在framework里面。 似乎没有办法hash

**Comment by TryImpossible** [comment]
感谢发现问题，周末抽时间看一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Navy ***@***.***&gt;
发送时间: 2024年1月4日 10:59
收件人: TryImpossible/flutter_web_optimizer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [TryImpossible/flutter_web_optimizer] Flutter3.16现在main.dart.js加载的是AssetManifest.bin.json文件，所以插件生成的AssetManifest.bin要修改下，不然不能加载资源文件 (Issue #29)





 
目前也可以手动解决此问题（自己写脚本）：
 1、执行flutter_web_optimizer，生成AssetManifest.bin
 2、使用base64将AssetManifest.bin文件转成base64编码的AssetManifest.bin.json文件
 3、将AssetManifest.bin.json首尾各添加1个字符引号"，如AssetManifest.bin.json里的内容为123，则变成"123"，再保存
 4、这样Flutter3.16的html打包也可以正常使用，不过canvaskit还是不行，待大佬解决

**Comment by TryImpossible** [comment]
感谢发现问题，周末抽时间看一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Nianxin ***@***.***&gt;
发送时间: 2024年1月4日 14:54
收件人: TryImpossible/flutter_web_optimizer ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [TryImpossible/flutter_web_optimizer] Flutter3.16现在main.dart.js加载的是AssetManifest.bin.json文件，所以插件生成的AssetManifest.bin要修改下，不然不能加载资源文件 (Issue #29)





 
3.16.5 的版本AssetManifest.bin.json的请求是写死在framework里面。 似乎没有办法hash

**Comment by liyingte998** [comment]
> 1、Flutter3.16现在加载AssetManifest.bin.json文件，所以插件生成的AssetManifest.bin要下，否则无法加载资源文件 2、Flutter3.13经过测试是没有问题的 3、canvaskit模式在Flutter3. 16和3.13，插件都不支持哦

3.13插件编译后的flutter_service_worker.js 没有修改，你使用没有问题吗

**Comment by liyingte998** [comment]
> > 1、Flutter3.16现在加载AssetManifest.bin.json文件，所以插件生成的AssetManifest.bin要下，否则无法加载资源文件 2、Flutter3.13经过测试是没有问题的 3、canvaskit模式在Flutter3. 16和3.13，插件都不支持哦
> 
> 3.13插件编译后的flutter_service_worker.js 没有修改，你使用没有问题吗？

3.13的flutter_service_worker.js
const RESOURCES = {"assets/AssetManifest.bin": "cd86dfd9e1638562a8455da636d5c901",
插件的正则String? resourcesValues = RegExp(r'const RESOURCES = {\n([\s\S]*)\n};')无法匹配到
需要手动换行

**Comment by navyzhou926** [comment]
> > > 1、Flutter3.16现在加载AssetManifest.bin.json文件，所以插件生成的AssetManifest.bin要下，否则无法加载资源文件 2、Flutter3.13经过测试是没有问题的 3、canvaskit模式在Flutter3. 16和3.13，插件都不支持哦
> > 
> > 
> > 3.13插件编译后的flutter_service_worker.js 没有修改，你使用没有问题吗？
> 
> 3.13的flutter_service_worker.js const RESOURCES = {"assets/AssetManifest.bin": "cd86dfd9e1638562a8455da636d5c901", 插件的正则String? resourcesValues = RegExp(r'const RESOURCES = {\n([\s\S]*)\n};')无法匹配到 需要手动换行

是的，Flutter3.13和3.16这个插件是没有替换的，需要打包后，自己写脚本生成AssetManifest.bin或AssetManifest.bin.json的hash文件名，然后在main.dart.js替换引用的文件名才行的

**Comment by TryImpossible** [comment]
@navyzhou926 , 1.4.0版本适配flutter 3.16版本 ，支持canvaskit模式
