### ISSUE TITLE
大佬您好，我使用了您的插件，发现字体和图片并没有被hash化，这是为啥呢？

### ISSUE THREAD

**Issue by LeeCareFree** [TryImpossible/flutter_web_optimizer#3]

**Comment by LeeCareFree** [comment]
![Uploading mmexport1671698087969.png…]()

**Comment by LeeCareFree** [comment]
![mmexport1671698087969](https://user-images.githubusercontent.com/51224246/209092575-0aeb6a1a-2bff-4ca7-8fd7-ff88bc3bc964.png)

**Comment by TryImpossible** [comment]
@LeeCareFree , js文件是有哈希化吗？你这是windows平台嘛？

**Comment by LeeCareFree** [comment]
> @LeeCareFree , js文件是有哈希化吗？你这是windows平台嘛？

js有的，图片和字体资源没有被hash化

**Comment by TryImpossible** [comment]
@LeeCareFree ，没有兼容windows平台，我抽空修复下这个问题

**Comment by TryImpossible** [comment]
@LeeCareFree ，flutter_web_optimizer: ^1.1.5版本已兼容windows平台，请使用

**Comment by LeeCareFree** [comment]
> @LeeCareFree ，flutter_web_optimizer: ^1.1.5版本已兼容windows平台，请使用

可以了，谢谢大佬。
