### ISSUE TITLE
Some image files are not related and Image not show.

### ISSUE THREAD

**Issue by KhunBaw** [TryImpossible/flutter_web_optimizer#5]
<img width="652" alt="1" src="https://user-images.githubusercontent.com/58159055/209555989-b0b5f242-c21c-4396-8eb6-94f793ec4062.png">
<img width="344" alt="2" src="https://user-images.githubusercontent.com/58159055/209556004-600c6ab8-d575-4535-9cdd-be40a0aa8c01.png">

**Comment by TryImpossible** [comment]
can you provide an demo?

**Comment by tienbm** [comment]
./assets/packages/wakelock_web/assets/no_sleep.js

**Comment by tienbm** [comment]
and it not load svg

**Comment by TryImpossible** [comment]
> it not change file this so it can't load ./assets/packages/wakelock_web/assets/no_sleep.js

@tienbm , this problem has been fixed. a version will be issued later

**Comment by tienbm** [comment]
> > it not change file this so it can't load ./assets/packages/wakelock_web/assets/no_sleep.js
> 
> @tienbm , this problem has been fixed. a version will be issued later

Thank. hope it will release soon

**Comment by tienbm** [comment]
![Uploading Screenshot 2023-01-10 at 18.04.28.png…]()

**Comment by tienbm** [comment]
![Screenshot 2023-01-10 at 18 04 28](https://user-images.githubusercontent.com/12368662/211535164-858f5585-6fda-4129-987c-35ea2307e5f5.png)
this is issue

**Comment by TryImpossible** [comment]
> ![Screenshot 2023-01-10 at 18 04 28](https://user-images.githubusercontent.com/12368662/211535164-858f5585-6fda-4129-987c-35ea2307e5f5.png) this is issue
@tienbm , this problem has been solved, a new version 1.1.6 has been released.

**Comment by tienbm** [comment]
> > ![Screenshot 2023-01-10 at 18 04 28](https://user-images.githubusercontent.com/12368662/211535164-858f5585-6fda-4129-987c-35ea2307e5f5.png) this is issue
> > @tienbm , this problem has been solved, a new version 1.1.6 has been released.

work pefect. thankyou

**Comment by TryImpossible** [comment]
> ![image](https://user-images.githubusercontent.com/12368662/211777075-66a931d5-4688-4e23-8b52-81d78fa90fd0.png) but there are still some problems from loading cache @TryImpossible

@tienbm , flutter_web_optimizer is not supported pwa

**Comment by tienbm** [comment]
> > ![image](https://user-images.githubusercontent.com/12368662/211777075-66a931d5-4688-4e23-8b52-81d78fa90fd0.png) but there are still some problems from loading cache @TryImpossible
> 
> @tienbm , flutter_web_optimizer is not supported pwa

so what should i do?

**Comment by TryImpossible** [comment]
flutter build web --web-renderer=html --release --source-maps --pwa-strategy none
@tienbm , add --pwa-strategy none disable pwa

**Comment by tienbm** [comment]
![image](https://user-images.githubusercontent.com/12368662/211972282-a43f79f0-0087-42d0-9fb4-61855b3bfb3f.png)
Svg problem solved but i still see some svg files still not loading by hash . I use func SvgPicture.asset of lib flutter_svg . ;(

**Comment by TryImpossible** [comment]
@tienbm , you can try a new version
