### ISSUE TITLE
不支持Flutter 3.3.10：Can't load Kernel binary: Invalid SDK hash.

### ISSUE THREAD

**Issue by sunjianan9900** [TryImpossible/flutter_web_optimizer#6]
```
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.0 22A380 darwin-arm (Rosetta),
    locale zh-Hans-CN)
environment:
  sdk: '>=2.18.5 <3.0.0'
```

```
Can't load Kernel binary: Invalid SDK hash.
No active package flutter_web_optimizer.
```

现在是不是不支持 Flutter 3.3.10 ？
怎么跳过SDK版本检查，不然的话以后flutter版本有更新插件没有更新就不能用了吧？

**Comment by sunjianan9900** [comment]
Can't load Kernel binary: Invalid SDK hash.
No active package flutter_web_optimizer.

**Comment by TryImpossible** [comment]
![image](https://user-images.githubusercontent.com/23582577/209787296-39bf4352-7898-4cb9-a1bb-763b5d4a8d40.png)
支持3.3.10版本，你这个错误是sdk的问题吧？

**Comment by TryImpossible** [comment]
@sunjianan9900

**Comment by sunjianan9900** [comment]
> @sunjianan9900
```
dart --version
Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "macos_arm64"
```

我本地的dart版本是最新的2.18.6
我把sdk那里换成2.18.6也不行，2.17.6也是这个错误提示
都做了flutter clean && flutter pub get 然后 flutter_web_optimizer optimize --asset-base http://127.0.0.1:8882/ --plugin scripts/upload.dart 的...

**Comment by TryImpossible** [comment]
@sunjianan9900 ,我刚刚在3.3.10版本上测试了，并没有出现你的错误。会不会是你本地环境的问题？你可以去搜索这个错误关键字。

**Comment by TryImpossible** [comment]
@sunjianan9900 ，你可以本地运行一个dart文件（就你自己写的，单纯个print也行），看会不会出现这个错误？

**Comment by sunjianan9900** [comment]
> 
破案了 flutter pub run flutter_web_optimizer  xxxx 就可以了，
直接运行 flutter_web_optimizer 就会有问题

因为升级之前我一直是直接用 flutter_web_optimizer 的，不知道为什么升级后不能用了

**Comment by TryImpossible** [comment]
https://dart.cn/tools/pub/cmd/pub-global
@sunjianan9900 ,可以了解下
